### PR TITLE
Changed map-select drop down menu, now it displays 'Map Name + Season' instead of file-name.

### PR DESCRIPTION
**Pull request by Marcii0**

### CODE REVIEW

**Comment by Marcii0** [comment]
by Host Server, I mean the "Host Server" tab *

**Review by PixieCore — COMMENTED** [review]
Implementation of the full map names isn't the best.

I commited a simpler and different version of achieving this.
If you are fine with those I would approve the PR and would get to merging it into the indev branch.

**Review by PixieCore — COMMENTED** [review]
Here is the implementation I commited.

**Review by PixieCore — COMMENTED** [review]
If the object is only used in 1 function but needs to remain static please define it likes this.

**Comment by Marcii0** [comment]
> Implementation of the full map names isn't the best.
> 
> I commited a simpler and different version of achieving this.
> If you are fine with those I would approve the PR and would get to merging it into the indev branch.

Yeah, that's fine, you are the one that knows a lot better than me afterall

**Pull request merged**
